/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  teachingSidebar: [
    {
      // Add a top-level item: Teaching
      type: 'category',
      label: 'Teaching',

      // Populate the category page with cards corresponding to each child in the hierarchy
      link: {
        type: 'generated-index',
        title: 'Teaching Resources',
        description: 'Currently Active Courses',
        slug: '/teaching',
        keywords: ['teaching'],
      },

      // Add to the sidebar all children in the hierarchy
      items: [
        {
          type: 'autogenerated',
          dirName: 'teaching',
        }]
    }],
    researchSidebar: [
    {
      // Add a top-level item: Teaching
      type: 'category',
      label: 'Research',

      // Populate the category page with cards corresponding to each child in the hierarchy
      link: {
        type: 'generated-index',
        title: 'Research Resources',
        description: 'Research topics and resources',
        slug: '/research',
        keywords: ['research'],
      },

      // Add to the sidebar all children in the hierarchy
      items: [
        {
          type: 'autogenerated',
          dirName: 'research',
        }]
    }
  ],


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
